---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart netbox-agent timer
  ansible.builtin.systemd:
    name: netbox-agent.timer
    state: restarted
  become: true
