set -g status-bg '#d16d9e'
set -g mouse on
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind s setw synchronize-panes
set -g status-right '#[fg=green]#H #[fg=yellow]%Y-%m-%d #[fg=cyan]%H:%M:%S'
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Change prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix
