---
- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  become: true

- name: Reload sshd
  ansible.builtin.systemd:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: reloaded
  become: true
