# Tailscale ExtensionServiceConfig for bihar (control-plane)
# Apply: talosctl -n 192.168.0.5 patch mc -p @talos-k8s/tailscale-bihar.yaml
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_AUTHKEY=tskey-client-kbWi3FDmr521CNTRL-sHsvAMfoND67W7vGP184E6h7ByeFgj5z
  - TS_HOSTNAME=bihar
  - TS_ROUTES=192.168.0.0/24
  - TS_ACCEPT_DNS=false
