set -g status-bg '#d16d9e'
set -g status-fg '#ffffff'
set -g mouse on
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind s setw synchronize-panes
set -g status-right '#H | %Y-%m-%d %H:%M'
set -g prefix C-a
unbind C-b
bind C-a send-prefix
