---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart NetBox
  ansible.builtin.systemd:
    name: netbox.service
    state: restarted
  become: true
