---
- name: Ensure passwordless sudo for current user
  ansible.builtin.copy:
    content: "{{ ansible_user_id | default(lookup('env', 'USER')) }} ALL=(ALL) NOPASSWD:ALL\n"
    dest: "/etc/sudoers.d/zz-{{ ansible_user_id | default(lookup('env', 'USER')) }}"
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
  become: true

- name: Remove old sudoers files
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
    - "99-{{ ansible_user_id | default(lookup('env', 'USER')) }}"
  become: true
