---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true
  failed_when: false

- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
  become: true
  changed_when: true
