context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = "Mic DSP"
      media.name = "Mic DSP"
      filter.graph = {
        nodes = [
          {
            type = ladspa
            name = rnnoise
            plugin = "librnnoise_ladspa"
            label = noise_suppressor_stereo
            control = {
              "VAD Threshold (%)" = 50.0
            }
          }
        ]
      }
      capture.props = {
        node.name = "effect_input.mic_dsp"
        node.description = "Microphone (DSP)"
        media.class = "Audio/Sink"
        priority.session = 2000
      }
      playback.props = {
        node.name = "effect_output.mic_dsp"
        node.description = "Microphone (DSP)"
        media.class = "Audio/Source"
        priority.session = 2000
      }
    }
  }
]
