is_arm: false
tailscale_advertise_routes: "192.168.0.0/24"
tailscale_accept_dns: false
tailscale_operator: james
web_services:
  - name: Proxmox
    href: https://bihar:8006
    icon: proxmox.png
    description: Hypervisor
    group: Infrastructure
    siteMonitor: https://bihar:8006
  - name: NetBox
    href: https://bihar:8444
    icon: netbox.png
    description: Network documentation
    group: Infrastructure
    siteMonitor: https://bihar:8444
  - name: Lima
    href: https://bihar/lima
    icon: mdi-virtual-machine
    description: VM dashboard + bootc builder
    group: Infrastructure
    siteMonitor: http://127.0.0.1:8007
  - name: Cockpit
    href: https://bihar:9090
    icon: cockpit.png
    description: System management
    group: System
    siteMonitor: https://bihar:9090
