is_arm: false
has_homepage: true
web_services:
  - name: Cockpit
    href: https://kanpur:9090
    icon: cockpit.png
    description: System management
    group: System
    siteMonitor: https://kanpur:9090
