---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart homepage
  ansible.builtin.systemd:
    name: homepage.service
    state: restarted
    scope: user
