---
- name: Reload systemd daemon
  ansible.builtin.command: systemctl daemon-reload
  become: true
  changed_when: false

- name: Restart homepage
  ansible.builtin.command: systemctl restart homepage.service
  become: true
  changed_when: true
