---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart homepage
  ansible.builtin.systemd:
    name: homepage.service
    state: restarted
  become: true
