---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted
    scope: user

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana.service
    state: restarted
    scope: user

- name: Restart loki
  ansible.builtin.systemd:
    name: loki.service
    state: restarted
    scope: user

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy.service
    state: restarted
    scope: user

- name: Restart promtail
  ansible.builtin.systemd:
    name: promtail.service
    state: restarted
    scope: user

- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager.service
    state: restarted
    scope: user

- name: Restart pve-exporter
  ansible.builtin.systemd:
    name: pve-exporter.service
    state: restarted
    scope: user

- name: Restart matrix-notifier
  ansible.builtin.systemd:
    name: matrix-notifier.service
    state: restarted
    scope: user
